In [1]:
import pandas as pd
movie_df = pd.read_csv('C:/Develop/深圳42/data/movie.csv')

- 1 把数据中所有 的James Cameron 替换成中文 詹姆斯·卡梅隆

In [2]:
movie_df.replace('James Cameron', '詹姆斯·卡梅隆', inplace=True)

In [4]:
movie_df['director_name'].value_counts()

Steven Spielberg    26
Woody Allen         22
Martin Scorsese     20
Clint Eastwood      20
Ridley Scott        16
                    ..
John Putch           1
Luca Guadagnino      1
Sam Fell             1
Dan Fogelman         1
Daniel Hsia          1
Name: director_name, Length: 2397, dtype: int64

- 2 查找数据集中上映年份(title_year)最近一年,   内容分级(content_rating)为 Not Rated 和  Unrated , imdb评分大于 6.6分的电影

In [10]:
movie_df[(movie_df['title_year'] == movie_df['title_year'].max()) & (movie_df['content_rating'].isin(['Not Rated','Unrated']) & (movie_df['imdb_score']>6.6))]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
3252,Color,Hong-jin Na,77.0,156.0,43.0,0.0,Jun Kunimura,45.0,770629.0,Fantasy|Horror|Mystery|Thriller,...,24.0,Korean,South Korea,Not Rated,NaN,2016.0,5.0,7.7,2.35,0

- 3 从数据集中选出如下列:
    - 电影名称 (movie_title), 导演姓名 (director_name), 主演名字(actor_1_name), 上映年份(title_year), imdb_score
    - 找到数据集中最近3年 评分最高的电影名称, 导演姓名, 主演名字, imdb_score分数

In [18]:
movie_df_2 = movie_df[['movie_title', 'director_name', 'actor_1_name', 'title_year','imdb_score']]
latest_3year = movie_df_2['title_year'].value_counts().sort_index(ascending=False).head(3).index
movie_df_2[movie_df_2['title_year'].isin(latest_3year)].sort_values(by='imdb_score', ascending=False).head(1)

,movie_title,director_name,actor_1_name,title_year,imdb_score
4312,Kickboxer: Vengeance,John Stockwell,Matthew Ziff,2016.0,9.1

- 4 找到2016年的imdb_score分数最高的5部电影, 给这5部电影构成的数据集添加一列, 取值为'年度最佳电影''

In [20]:
head_5df = movie_df_2[movie_df_2['title_year']==2016].sort_values(by='imdb_score', ascending=False).head(5)
head_5df['电影类型'] ='年度最佳电影'

In [21]:
head_5df

,movie_title,director_name,actor_1_name,title_year,imdb_score,电影类型
4312,Kickboxer: Vengeance,John Stockwell,Matthew Ziff,2016.0,9.1,年度最佳电影
4277,A Beginner's Guide to Snuff,Mitchell Altieri,Kimberley Crossman,2016.0,8.7,年度最佳电影
3798,Airlift,Raja Menon,Nimrat Kaur,2016.0,8.5,年度最佳电影
98,Godzilla Resurgence,Hideaki Anno,Mark Chinnery,2016.0,8.2,年度最佳电影
27,Captain America: Civil War,Anthony Russo,Robert Downey Jr.,2016.0,8.2,年度最佳电影

- 5 给电影数据集添加一列, 利润 , 用gross 收入 - budget 预算  放到 budget列后面

In [24]:
movie_df['profite']=movie_df['gross']-movie_df['budget']
movie_df.insert(loc=23,column='profite',value=movie_df['gross']-movie_df['budget'],allow_duplicates=True)

In [28]:
movie_df['profite']

          profite      profite
0     523505847.0  523505847.0
1       9404152.0    9404152.0
2     -44925825.0  -44925825.0
3     198130642.0  198130642.0
4             NaN          NaN
...           ...          ...
4911          NaN          NaN
4912          NaN          NaN
4913          NaN          NaN
4914          NaN          NaN
4915      84122.0      84122.0

[4916 rows x 2 columns]

- 6 把数据中的movie_facebook_likes 列删除

In [29]:
movie_df.drop('movie_facebook_likes', axis=1, inplace=True)

In [31]:
movie_df['movie_facebook_likes']

KeyError: 'movie_facebook_likes'

- 7 筛选出2016年的电影作为一个新的df, 把2016年的电影中, imdb评分数低于7分的电影删掉

In [37]:
drop_list = movie_df_2[(movie_df_2['title_year']==2016) & (movie_df_2['imdb_score']<7)].index
movie_df_2.drop(drop_list)

,movie_title,director_name,actor_1_name,title_year,imdb_score
0,Avatar,詹姆斯·卡梅隆,CCH Pounder,2009.0,7.9
1,Pirates of the Caribbean: At World's End,Gore Verbinski,Johnny Depp,2007.0,7.1
2,Spectre,Sam Mendes,Christoph Waltz,2015.0,6.8
3,The Dark Knight Rises,Christopher Nolan,Tom Hardy,2012.0,8.5
4,Star Wars: Episode VII - The Force Awakens,Doug Walker,Doug Walker,NaN,7.1
...,...,...,...,...,...
4911,Signed Sealed Delivered,Scott Smith,Eric Mabius,2013.0,7.7
4912,The Following,NaN,Natalie Zea,NaN,7.5
4913,A Plague So Pleasant,Benjamin Roberds,Eva Boehnke,2013.0,6.3
4914,Shanghai Calling,Daniel Hsia,Alan Ruck,2012.0,6.3
4915,My Date with Drew,Jon Gunn,John August,2004.0,6.6

- 8 找到数据集中, 主演电影数量最多的5位演员, 保存到Mysql中, 保存两个字段, 姓名和出演电影数量

In [ ]:
from sqlalchemy import create_engine
engine = create_engine('mysql+pymysql://root:@/movies.db')