In [3]:
import pandas as pd
import statsmodels.stats.api as sms
# 计算参与实验的人数
effect_size = sms.proportion_effectsize(0.13,0.15) # 0.13 是当前的转化率, 0.15 目标转化率
required_n = sms.NormalIndPower().solve_power(effect_size,power=0.8,alpha=0.05,ratio=1) #power 1-β 0.8   alpha 显著性水平, 一般就是5%

In [4]:
from math import ceil
# ceil向上去整数
required_n =ceil(required_n)
required_n

4720

In [21]:
ab_data = pd.read_csv('C:/Develop/深圳42/data/ab_data.csv')
ab_data.head()

   user_id                   timestamp      group landing_page  converted
0   851104  2017-01-21 22:11:48.556739    control     old_page          0
1   804228  2017-01-12 08:01:45.159739    control     old_page          0
2   661590  2017-01-11 16:55:06.154213  treatment     new_page          0
3   853541  2017-01-08 18:28:03.143765  treatment     new_page          0
4   864975  2017-01-21 01:52:26.210827    control     old_page          1

In [6]:
ab_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294478 entries, 0 to 294477
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   user_id       294478 non-null  int64
 1   timestamp     294478 non-null  object
 2   group         294478 non-null  object
 3   landing_page  294478 non-null  object
 4   converted     294478 non-null  int64
dtypes: int64(2), object(3)
memory usage: 11.2+ MB

In [8]:
ab_data['group'].value_counts()

treatment    147276
control      147202
Name: group, dtype: int64

In [9]:
ab_data['landing_page'].value_counts()

old_page    147239
new_page    147239
Name: landing_page, dtype: int64

In [22]:
session_counts = ab_data['user_id'].value_counts()

In [23]:
users = session_counts[session_counts<2].index
ab_data=ab_data[ab_data['user_id'].isin(users)]

In [11]:
ab_data.shape[0]

294478

In [14]:
ab_data[ab_data['user_id']==754884]

        user_id                   timestamp      group landing_page  converted
236842   754884  2017-01-18 20:10:48.538515  treatment     old_page          0
245524   754884  2017-01-17 23:46:45.624036  treatment     new_page          0

In [37]:
# 从数据中采样 4720个
control_sample = ab_data[ab_data['group']=='control'].sample(n=required_n,random_state=13) # 对照组 看老页面
test_sample = ab_data[ab_data['group']=='treatment'].sample(n=required_n,random_state=13) # 实验组 看新页面
control_sample['converted'].mean()

0.12012711864406779

In [30]:
 # 转化率  购买人数/总访问人数

0.12330508474576271

In [38]:
test_sample['converted'].mean()

0.12266949152542372