In [4]:
import pandas as pd
app_store = pd.read_csv('C:/Develop/深圳42/data/applestore.csv',index_col=0)

- 背景
  - 对APP下载和评分数据分析帮助App开发者获取和留存用户
  - 通过对应用商店的数据分析为开发人员提供可操作的意见
- 通过数据分析要解决的问题
  - 免费和收费的App都集中在哪些类别
  - 收费app的价格是如何分布的，不同类别的价格分布怎样
  - App文件的大小和价格以及用户评分之间是否有关

数据字段说明
  - id : App ID 每个App唯一标识
  - track_name: App的名称
  - size_bytes: 以byte为单位的app大小
  - price：定价（美元）
  - rating_count_tot: App所有版本的用户评分数量
  - rating_count_ver: App当前版本的用户评分数量
  - prime_genre: App的类别
  - user_rating: App所有版本的用户评分
  - sup_devices.num: 支持的iOS设备数量
  - ipadSc_urls.num: app提供的截屏展示数量
  - lang.num 支持的语言数量

In [5]:
app_store.head()

,id,track_name,size_bytes,price,rating_count_tot,user_rating,prime_genre,sup_devices,ipadSc_urls,lang
0,281656475,PAC-MAN Premium,100788224,3.99,21292,4.0,Games,38,5,10
1,281796108,Evernote - stay organized,158578688,0.00,161065,4.0,Productivity,37,5,23
2,281940292,"WeatherBug - Local Weather, Radar, Maps, Alerts",100524032,0.00,188583,3.5,Weather,37,5,3
3,282614216,"eBay: Best App to Buy, Sell, Save! Online Shop...",128512000,0.00,262241,4.0,Shopping,37,5,9
4,282935706,Bible,92774400,0.00,985920,4.5,Reference,37,5,45

In [6]:
app_store.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7197 entries, 0 to 7196
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                7197 non-null   int64
 1   track_name        7197 non-null   object
 2   size_bytes        7197 non-null   int64
 3   price             7197 non-null   float64
 4   rating_count_tot  7197 non-null   int64
 5   user_rating       7197 non-null   float64
 6   prime_genre       7197 non-null   object
 7   sup_devices       7197 non-null   int64
 8   ipadSc_urls       7197 non-null   int64
 9   lang              7197 non-null   int64
dtypes: float64(2), int64(6), object(2)
memory usage: 618.5+ KB

In [7]:
app_store.describe()

,id,size_bytes,price,rating_count_tot,user_rating,sup_devices,ipadSc_urls,lang
count,7.197000e+03,7.197000e+03,7197.000000,7.197000e+03,7197.000000,7197.000000,7197.000000,7197.000000
mean,8.631310e+08,1.991345e+08,1.726218,1.289291e+04,3.526956,37.361817,3.707100,5.434903
std,2.712368e+08,3.592069e+08,5.833006,7.573941e+04,1.517948,3.737715,1.986005,7.919593
min,2.816565e+08,5.898240e+05,0.000000,0.000000e+00,0.000000,9.000000,0.000000,0.000000
25%,6.000937e+08,4.692275e+07,0.000000,2.800000e+01,3.500000,37.000000,3.000000,1.000000
50%,9.781482e+08,9.715302e+07,0.000000,3.000000e+02,4.000000,37.000000,5.000000,1.000000
75%,1.082310e+09,1.819249e+08,1.990000,2.793000e+03,4.500000,38.000000,5.000000,8.000000
max,1.188376e+09,4.025970e+09,299.990000,2.974676e+06,5.000000,47.000000,5.000000,75.000000