In [1]:
import pandas as pd
uniqlo = pd.read_csv('C:/Develop/顺义48/day01/02_代码/data/uniqlo.csv')
uniqlo.head()

   店铺id  城市 销售渠道      性别    年龄段     消费时间  产品名称  客户数量   销售金额  订单数量  产品数量  单件成本
0   658  深圳   线下  Female  25-29  Weekday  当季新品     4  796.0     4     4    59
1   146  杭州   线下  Female  25-29  Weekday    运动     1  149.0     1     1    49
2    70  深圳   线下    Male   >=60  Weekday    T恤     2  178.0     2     2    49
3   658  深圳   线下  Female  25-29  Weekday    T恤     1   59.0     1     1    49
4   229  深圳   线下    Male  20-24  Weekend    袜子     2   65.0     2     3     9

In [ ]:
# 这次作业相对来比较开放, 综合运用之前所学的知识, 尽可能的从不同维度来分析问题
# 比如 统计不同产品的销售情况, 可以按照不同的维度进行进一步拆解
#  不同产品 按线上线下, 按性别, 按年龄段等等...
# 最终要给出文字结论

In [31]:
uniqlo[uniqlo['销售金额']<0]

,店铺id,城市,销售渠道,性别,年龄段,消费时间,产品名称,客户数量,销售金额,订单数量,产品数量,单件成本
20049,91,武汉,线上,Female,55-59,Weekday,运动,1,-0.66,1,2,49

## 1 不同产品的销售情况

### 1.1 统计不同产品的销售总量

In [2]:
uniqlo.groupby(['产品名称'])[['订单数量','销售金额']].sum()

       订单数量        销售金额
产品名称
T恤    16792  1538744.84
当季新品   4835   590664.88
毛衣     1258   245630.80
牛仔裤    2292   246127.48
短裤     2375   107485.88
袜子     2775   127731.36
裙子      980   137302.78
运动     1538   118059.68
配件     3983   444685.15

### 1.2 按城市统计不同产品类别的销售总量

In [3]:
uniqlo.pivot_table(index='城市',columns='产品名称',values=['订单数量','销售金额'],aggfunc='sum')

      订单数量                                               销售金额             \
产品名称    T恤 当季新品   毛衣  牛仔裤   短裤   袜子   裙子   运动   配件         T恤       当季新品
城市
上海    1865  502  117  287  264  285  100  153  464  175416.04   55274.81
北京     732  157   37   43   71   90   27   25  121   70349.96   18854.86
南京     519  221   42   50   46   82   26   16  111   47702.91   36697.68
广州    1549  425  130  179  204  299  104  146  356  140886.72   45568.95
成都     975  301   89  171  152  196   76  105  198   89127.68   35935.63
杭州    2820  783  205  359  390  502  158  313  666  253602.43   99377.30
武汉    2708  803  197  392  409  438  163  239  647  253268.13   96418.88
深圳    3378  983  236  452  505  524  200  299  898  309042.79  127637.43
西安    1070  256   97  145  151  152   70  102  236   94885.94   28266.76
重庆    1176  404  108  214  183  207   56  140  286  104462.24   46632.58


产品名称        毛衣       牛仔裤        短裤        袜子        裙子        运动         配件
城市
上海    23785.67  32017.40  11659.42  13715.94  14973.93  11383.17   51595.35
北京     7210.68   4309.00   3241.67   4658.24   3829.55   2214.00   15790.66
南京     7525.10   5753.63   1836.22   4258.62   4168.00   1406.34   13802.43
广州    24871.00  16126.90   9914.99  13515.61  13945.56  10367.99   42926.77
成都    15638.33  14922.04   7103.22   8095.41  10160.33   7678.66   19528.56
杭州    45169.62  36259.89  17715.38  21559.65  21385.04  23875.08   70574.10
武汉    38830.63  47505.29  18603.66  20581.63  23755.26  17867.32   72946.98
深圳    44161.03  50120.39  23214.33  25822.56  27572.11  24339.68  101213.36
西安    18426.74  15865.32   6468.88   6425.47   9417.00   7015.47   24003.04
重庆    20012.00  23247.62   7728.11   9098.23   8096.00  11911.97   32303.90

### 1.3 进一步按城市以及线上线下分析

In [4]:
uniqlo.pivot_table(index=['城市','销售渠道'],columns='产品名称',values=['订单数量','销售金额'],aggfunc='sum')

         订单数量                                               销售金额             \
产品名称       T恤 当季新品   毛衣  牛仔裤   短裤   袜子   裙子   运动   配件         T恤       当季新品
城市 销售渠道
上海 线上     542  158   25   87   99   89   34   38  165   48637.48   16136.50
   线下    1323  344   92  200  165  196   66  115  299  126778.56   39138.31
北京 线下     732  157   37   43   71   90   27   25  121   70349.96   18854.86
南京 线下     519  221   42   50   46   82   26   16  111   47702.91   36697.68
广州 线上     995  252   77  112  126  193   44   90  226   93729.71   26574.95
   线下     554  173   53   67   78  106   60   56  130   47157.01   18994.00
成都 线下     975  301   89  171  152  196   76  105  198   89127.68   35935.63
杭州 线下    2820  783  205  359  390  502  158  313  666  253602.43   99377.30
武汉 线上    1285  294  113  151  227  231   62   88  444  120358.13   32243.46
   线下    1423  509   84  241  182  207  101  151  203  132910.00   64175.42
深圳 线下    3378  983  236  452  505  524  200  299  898  309042.79  127637.43
西安 线上     114   37    5   27   23   33   17   24   45   11311.93    4158.34
   线下     956  219   92  118  128  119   53   78  191   83574.01   24108.42
重庆 线上      83   47   16   13   35   22    1   17   17    7894.00    5138.00
   线下    1093  357   92  201  148  185   55  123  269   96568.24   41494.58


产品名称           毛衣       牛仔裤        短裤        袜子        裙子        运动         配件
城市 销售渠道
上海 线上     5019.00   9264.93   4453.04   4379.45   5341.00   2264.00   18942.69
   线下    18766.67  22752.47   7206.38   9336.49   9632.93   9119.17   32652.66
北京 线下     7210.68   4309.00   3241.67   4658.24   3829.55   2214.00   15790.66
南京 线下     7525.10   5753.63   1836.22   4258.62   4168.00   1406.34   13802.43
广州 线上    14410.00   9957.90   6433.92   8791.61   5932.00   6438.67   28624.54
   线下    10461.00   6169.00   3481.07   4724.00   8013.56   3929.32   14302.23
成都 线下    15638.33  14922.04   7103.22   8095.41  10160.33   7678.66   19528.56
杭州 线下    45169.62  36259.89  17715.38  21559.65  21385.04  23875.08   70574.10
武汉 线上    22981.63  19537.13   9894.47  10715.32  10086.00   6106.36   49498.23
   线下    15849.00  27968.16   8709.19   9866.31  13669.26  11760.96   23448.75
深圳 线下    44161.03  50120.39  23214.33  25822.56  27572.11  24339.68  101213.36
西安 线上     1095.00   3043.00   1127.00   1458.00   2331.00   1386.20    4177.54
   线下    17331.74  12822.32   5341.88   4967.47   7086.00   5629.27   19825.50
重庆 线上     3228.00   2421.00   1578.88   1074.00    199.00   2627.47    2170.00
   线下    16784.00  20826.62   6149.23   8024.23   7897.00   9284.50   30133.90

## 2 用户习惯使用哪种方式进行消费 (线上还是线下)

In [6]:
online_list = ['上海','广州','武汉','西安','重庆']
uniqlo_online = uniqlo[uniqlo['城市'].isin(online_list)]
uniqlo_online.pivot_table(index=['销售渠道','性别'],columns='产品名称',values=['订单数量'],aggfunc='sum')

               订单数量
产品名称             T恤    当季新品     毛衣    牛仔裤     短裤     袜子     裙子     运动     配件
销售渠道 性别
线上   Female  2078.0   539.0  130.0  320.0  240.0  313.0  131.0  138.0  675.0
     Male     925.0   247.0  106.0   65.0  267.0  254.0   27.0  119.0  217.0
     Unkown    16.0     2.0    NaN    5.0    3.0    1.0    NaN    NaN    5.0
线下   Female  3920.0  1128.0  244.0  686.0  374.0  522.0  276.0  352.0  822.0
     Male    1414.0   473.0  168.0  139.0  326.0  286.0   59.0  170.0  266.0
     Unkown    15.0     1.0    1.0    2.0    1.0    5.0    NaN    1.0    4.0

In [8]:
uniqlo_online.pivot_table(index='销售渠道',columns='性别',values='订单数量',aggfunc='sum',margins=True)

性别    Female  Male  Unkown    All
销售渠道
线上      4564  2227      32   6823
线下      8324  3301      30  11655
All    12888  5528      62  18478

In [9]:
uniqlo_online.pivot_table(index='销售渠道',columns='年龄段',values='订单数量',aggfunc='sum',margins=True)

年龄段,20-24,25-29,30-34,35-39,40-44,45-49,50-54,55-59,<20,>=60,Unkown,All
销售渠道,,,,,,,,,,,,
线上,1083,1671,1594,988,435,233,143,104,134,404,34,6823
线下,1637,2243,2589,2265,949,493,346,222,217,654,40,11655
All,2720,3914,4183,3253,1384,726,489,326,351,1058,74,18478

- 有些城市没有线上, 只有线下  (北京 南京 杭州 深圳)

## 3 用户消费时间习惯 (周间还是周末)

In [14]:
temp_df = uniqlo.groupby(['消费时间'])[['订单数量']].sum()

In [15]:
temp_df['days'] = [5,2]

In [17]:
temp_df['订单数量']/temp_df['days']

消费时间
Weekday    4336.4
Weekend    7573.0
dtype: float64

In [23]:
temp_df = uniqlo.pivot_table(index='城市',columns='消费时间',values='订单数量',aggfunc='sum')
temp_df['周间平均'] = temp_df['Weekday']/5

In [26]:
temp_df['周末平均'] = temp_df['Weekend']/2

In [28]:
temp_df['周间平均']/temp_df['周末平均']

城市
上海    0.529649
北京    0.583396
南京    0.696552
广州    0.617854
成都    0.636884
杭州    0.587410
武汉    0.585779
深圳    0.557719
西安    0.491977
重庆    0.540339
dtype: float64

In [29]:
temp_df

消费时间  Weekday  Weekend   周间平均    周末平均
城市
上海       2300     1737  460.0   868.5
北京        773      530  154.6   265.0
南京        707      406  141.4   203.0
广州       2059     1333  411.8   666.5
成都       1390      873  278.0   436.5
杭州       3686     2510  737.2  1255.0
武汉       3563     2433  712.6  1216.5
深圳       4353     3122  870.6  1561.0
西安       1257     1022  251.4   511.0
重庆       1594     1180  318.8   590.0