In [1]:
import pandas as pd
df = pd.read_csv('C:/Develop/深圳42/data/LJdata.csv')

# 分组聚合

In [7]:
df.groupby('区域').mean()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_22416\3271004694.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('区域').mean()

                 面积            价格       看房人数
区域
CBD租房    113.375000  14700.000000   6.750000
七里庄租房     82.941176   5617.647059  13.764706
万寿路租房     63.875000   6575.000000  14.875000
万柳租房     137.916667  18629.166667  16.541667
三元桥租房    103.045455  12581.818182  12.590909
...             ...           ...        ...
鲁谷租房      80.684211   6381.578947  11.421053
黄村中租房     84.000000   3775.000000   3.250000
黄村北租房    104.684211   5631.578947  14.473684
黄村火车站租房   77.666667   3166.666667   7.666667
鼓楼大街租房    89.000000   3987.500000   6.937500

[208 rows x 3 columns]

In [10]:
df.groupby('区域')['价格'].mean()

区域
CBD租房      14700.000000
七里庄租房       5617.647059
万寿路租房       6575.000000
万柳租房       18629.166667
三元桥租房      12581.818182
               ...
鲁谷租房        6381.578947
黄村中租房       3775.000000
黄村北租房       5631.578947
黄村火车站租房     3166.666667
鼓楼大街租房      3987.500000
Name: 价格, Length: 208, dtype: float64

In [14]:
df.groupby('区域')[['面积','价格']].mean()

                 面积            价格
区域
CBD租房    113.375000  14700.000000
七里庄租房     82.941176   5617.647059
万寿路租房     63.875000   6575.000000
万柳租房     137.916667  18629.166667
三元桥租房    103.045455  12581.818182
...             ...           ...
鲁谷租房      80.684211   6381.578947
黄村中租房     84.000000   3775.000000
黄村北租房    104.684211   5631.578947
黄村火车站租房   77.666667   3166.666667
鼓楼大街租房    89.000000   3987.500000

[208 rows x 2 columns]

In [19]:
df.groupby('区域')[['面积','价格']].agg(['mean','median']).columns

MultiIndex([('面积',   'mean'),
            ('面积', 'median'),
            ('价格',   'mean'),
            ('价格', 'median')],
           )

In [21]:
result_df = df.groupby('区域')[['面积','价格']].agg(['mean','median'])
result_df[('面积',   'mean')]

区域
CBD租房      113.375000
七里庄租房       82.941176
万寿路租房       63.875000
万柳租房       137.916667
三元桥租房      103.045455
              ...
鲁谷租房        80.684211
黄村中租房       84.000000
黄村北租房      104.684211
黄村火车站租房     77.666667
鼓楼大街租房      89.000000
Name: (面积, mean), Length: 208, dtype: float64

In [22]:
df.groupby('区域').agg({'面积':'mean','价格':'median'})

                 面积       价格
区域
CBD租房    113.375000  14000.0
七里庄租房     82.941176   5500.0
万寿路租房     63.875000   6300.0
万柳租房     137.916667  19750.0
三元桥租房    103.045455  12500.0
...             ...      ...
鲁谷租房      80.684211   5500.0
黄村中租房     84.000000   3550.0
黄村北租房    104.684211   5200.0
黄村火车站租房   77.666667   3300.0
鼓楼大街租房    89.000000   4000.0

[208 rows x 2 columns]

In [27]:
df.groupby(['区域','户型']).agg({'面积':'mean','价格':'median'})

                     面积       价格
区域     户型
CBD租房  1室1厅   60.000000  11500.0
       2室1厅  110.250000  16000.0
       2室2厅  161.000000  16000.0
       3室1厅  172.666667  22000.0
       4室2厅  173.000000  18000.0
...                 ...      ...
鼓楼大街租房 1室0厅   37.000000   1900.0
       1室1厅   41.000000   1800.0
       2室1厅   78.250000   4000.0
       2室2厅   89.000000   4000.0
       3室1厅  104.888889   4800.0

[793 rows x 2 columns]

In [34]:
df.groupby(['区域','户型'],as_index=False).agg({'面积':'mean','价格':'median'})

         区域    户型          面积       价格
0     CBD租房  1室1厅   60.000000  11500.0
1     CBD租房  2室1厅  110.250000  16000.0
2     CBD租房  2室2厅  161.000000  16000.0
3     CBD租房  3室1厅  172.666667  22000.0
4     CBD租房  4室2厅  173.000000  18000.0
..      ...   ...         ...      ...
788  鼓楼大街租房  1室0厅   37.000000   1900.0
789  鼓楼大街租房  1室1厅   41.000000   1800.0
790  鼓楼大街租房  2室1厅   78.250000   4000.0
791  鼓楼大街租房  2室2厅   89.000000   4000.0
792  鼓楼大街租房  3室1厅  104.888889   4800.0

[793 rows x 4 columns]

In [35]:
df.columns

Index(['区域', '地址', '户型', '面积', '价格', '朝向', '更新时间', '看房人数'], dtype='object')

In [37]:
groupby_result = df.groupby(['区域', '地址', '户型']).agg({'面积':['min','max'],'价格':'mean','看房人数':'median'})

In [41]:
groupby_result.loc[('CBD租房','盛世嘉园'),'面积']

      min  max
户型
2室1厅  132  132
2室2厅  161  161

## Groupby 分组聚合过程说明

In [42]:
df.groupby('区域')['价格'].mean()

区域
CBD租房      14700.000000
七里庄租房       5617.647059
万寿路租房       6575.000000
万柳租房       18629.166667
三元桥租房      12581.818182
               ...
鲁谷租房        6381.578947
黄村中租房       3775.000000
黄村北租房       5631.578947
黄村火车站租房     3166.666667
鼓楼大街租房      3987.500000
Name: 价格, Length: 208, dtype: float64

In [44]:
df_gby = df.groupby('区域') # DataFrameGroupby对象

In [59]:
df_gby.groups

{'CBD租房': [624, 645, 693, 1359, 1363, 1383, 1387, 1719, 1755, 1840, 1864, 1958, 1993, 2073, 2288, 2562], '七里庄租房': [117, 138, 144, 154, 297, 300, 1065, 1085, 1440, 1516, 1941, 1952, 1962, 1963, 2099, 2189, 2191], '万寿路租房': [168, 466, 469, 968, 1466, 1881, 2338, 2655], '万柳租房': [233, 464, 467, 481, 510, 589, 596, 627, 671, 851, 853, 917, 952, 1235, 1240, 1471, 1497, 1517, 1690, 1846, 2418, 2495, 2574, 2631], '三元桥租房': [95, 245, 338, 699, 777, 802, 811, 1109, 1197, 1216, 1512, 1518, 1572, 1798, 1818, 1843, 1942, 1949, 1978, 2065, 2277, 2759], '三里屯租房': [753, 793, 1162, 1275, 2152, 2488], '上地租房': [54, 67, 68, 169, 885, 1223, 1245, 1618, 2149, 2183, 2417, 2433], '世纪城租房': [171, 222, 281, 320, 339, 858, 1024, 1449, 1464, 1741, 1751, 1772, 2011, 2013, 2497, 2712], '东关租房': [335, 617, 638, 678, 965, 980, 1081, 1335, 1749, 2095, 2226, 2428, 2474, 2493, 2613, 2731], '东四租房': [2187, 2584], '东坝租房': [75, 97, 546, 845], '东大桥租房': [1051, 1770, 2115, 2135], '东直门租房': [58, 116, 136, 152, 220, 226, 240, 381, 405, 488, 517, 575, 662, 1255, 1281, 1543, 1582, 1590, 1666, 2706], '东花市租房': [473, 1171, 1498, 1548, 1595, 1748, 2003, 2688], '中关村租房': [1017, 1110, 1179, 1294, 2218, 2219, 2220], '临河里租房': [84, 694, 775, 1035, 1038, 1330, 1480, 1495, 1540, 1574, 1637, 1746, 1799, 1819, 1820, 1842, 1866, 2459, 2734], '丽泽租房': [1885], '乔庄租房': [87, 461, 569, 602, 956, 1358, 1360, 1382, 1384, 1663], '九棵树(家乐福)租房': [404, 716, 875, 886, 1036, 1211, 1487, 1515, 1533, 1555, 1601, 1703, 1756, 1796, 1812, 1897, 2032, 2039, 2041, 2042, 2123, 2143, 2320, 2462, 2542, 2552, 2609, 2729, 2748], '二里庄租房': [110, 384, 815], '五棵松租房': [140, 156, 263, 626, 647, 725, 991, 1102, 1139, 1237, 1494, 1504, 1868, 2464], '五道口租房': [271, 499, 528, 565, 995, 1529, 1531, 2131, 2161, 2206], '五里店租房': [2264], '亚运村小营租房': [279, 599, 735, 1199, 1247, 1277, 1300, 1392, 1405, 1412, 1524, 1573, 1617, 1757, 1862, 1886, 1888, 1906, 2084, 2145, 2198, 2416, 2535, 2544, 2554, 2577, 2629, 2678], '亚运村租房': [385, 491, 520, 568, 883, 1050, 1060, 1068, 1088, 1093, 1166, 1185, 1538, 1562, 1786, 1821, 1826, 2134, 2164, 2356, 2471, 2635, 2687, 2699, 2700], '交道口租房': [244, 768, 808, 2614], '亦庄开发区其它租房': [328, 1557, 2652], '亦庄租房': [210, 234, 284, 359, 364, 564, 884, 1008, 1023, 1115, 1157, 1207, 1453, 1511, 1530, 1535, 1622, 1654, 1822, 1841, 1858, 1865, 1895, 1930, 1968, 2242, 2254, 2305, 2537, 2567, 2579, 2581, 2597, 2599], '健翔桥租房': [11, 749, 761], '公主坟租房': [287, 315, 452, 588, 707, 788, 1251, 1308, 1309, 1378, 1677, 2222, 2234, 2713, 2737], '六里桥租房': [29, 33, 141, 147, 157, 396, 419, 581, 713, 1145, 1177, 1206, 1214, 1345, 1416, 1623, 1624, 2002, 2247, 2273, 2325, 2419, 2757], '六铺炕租房': [450, 764, 927, 1129, 1625, 1669, 2129, 2266, 2337, 2376, 2715], '军博租房': [163, 484, 513, 566, 784, 923, 1426, 1893, 2500], '农展馆租房': [1556, 1602], '冯村租房': [683], '刘家窑租房': [15, 1564, 1792, 1808], '劲松租房': [118, 145, 195, 323, 330, 344, 347, 451, 595, 771, 915, 1004, 1257, 1260, 1545, 1592, 2096, 2396, 2436, 2438, 2708], '北七家租房': [409, 540, 544, 726, 812, 878, 983, 1000, 1034, 1424, 1462, 1702, 1829, 1956, 2004, 2197, 2445, 2517, 2519, 2523, 2525, 2531, 2586], '北京南站租房': [456, 800, 1198, 1222, 1321], '北关租房': [310, 509, 538, 591, 629, 909, 1170, 1689, 1692, 1800, 1828, 1914], '北大地租房': [24, 247, 368, 430, 1133, 1271, 1542, 1563, 1725, 1726, 2087, 2102, 2172, 2208, 2645, 2647], '北太平庄租房': [2014], '北工大租房': [813, 1030, 1284, 2298, 2622], '北苑租房': [6, 9, 18, 96, 114, 122, 134, 149, 165, 166, 198, 205, 231, 252, 299, 302, 304, 329, 353, 403, 571, 586, 692, 757, 854, 867, 870, 874, 894, 963, 975, 990, 1103, 1105, 1121, 1141, 1165, 1180, 1192, 1208, 1306, 1393, 1428, 1469, 1477, 1509, 1612, 1621, 1647, 1672, 1697, 1728, 1762, 1789, 1900, 1943, 1948, 1977, 1999, 2006, 2107, 2292, 2302, 2347, 2361, 2502, 2509, 2539, 2564, 2576, 2585, 2595, 2602, 2603, 2642, 2644, 2656, 2697, 2726], '十里堡租房': [199, 425, 504, 533, 881, 899, 943, 1479, 1508, 1630, 1817, 1965, 2059, 2062, 2210, 2480], '华威桥租房': [348, 1236, 1554, 1600, 2314], '南口租房': [2610], '南沙滩租房': [266, 1021, 1338, 1490, 1500, 1979, 2056], '南邵租房': [185, 1745, 1857, 1951], '卢沟桥租房': [74, 414, 449, 705, 759, 797, 1151, 1175, 1626, 1876, 2159, 2170, 2195, 2422], '厂洼租房': [2306], '双井租房': [14, 34, 71, 113, 123, 201, 227, 291, 305, 388, 394, 468, 485, 514, 558, 664, 666, 704, 708, 722, 774, 935, 951, 966, 1025, 1028, 1043, 1213, 1215, 1229, 1246, 1314, 1441, 1448, 1475, 1493, 1503, 1678, 1838, 1860, 1973, 1983, 2015, 2020, 2026, 2051, 2171, 2365, 2412, 2421, 2501, 2507, 2533, 2570, 2604], '双桥租房': [83, 1066, 1086, 1254, 1616, 1627, 1934, 2097, 2389, 2455, 2588], '双榆树租房': [249, 801, 810, 1176, 1230, 1231, 1670, 2255, 2672, 2752], '古城租房': [700, 1659, 2276], '右安门内租房': [987, 989, 1002, 1347, 2066, 2547, 2557], '右安门外租房': [805, 814, 818, 1063, 1083, 1279, 1339, 1668, 1739], '后沙峪租房': [371, 433, 828, 907, 1009, 1269, 1521, 1532, 1649, 1680, 1825, 1887, 2071, 2106, 2373, 2423, 2548, 2558], '和义租房': [1071, 1091], '和平里租房': [10, 108, 262, 264, 417, 739, 789, 1039, 1146, 1224, 1225, 1552, 1599, 1644, 1657, 2047, 2088, 2111, 2249, 2275, 2289, 2370, 2374, 2658], '四季青租房': [19, 107, 382, 619, 640, 911, 949, 1045, 1127, 1268, 1310, 1486, 1650, 1890, 1910, 2538], '四惠租房': [104, 721, 752, 792, 1018, 1135, 1174, 1742, 1753, 1774, 1791, 1807, 1856, 2114, 2217, 2228, 2252, 2453, 2650], '回龙观租房': [5, 25, 46, 62, 82, 85, 135, 246, 288, 321, 345, 357, 362, 416, 454, 496, 525, 548, 551, 600, 636, 779, 830, 847, 905, 947, 1014, 1317, 1352, 1355, 1419, 1423, 1465, 1651, 1673, 1803, 1918, 1932, 1990, 2300, 2344, 2601], '团结湖租房': [4, 238, 979, 1079, 1137, 1140, 1944, 1945, 1974, 2304, 2327], '国展租房': [455, 839, 1451, 1711, 2053], '地安门租房': [256], '垡头租房': [580, 620, 641, 2190], '城子租房': [754, 794, 1003, 2681], '大兴其它租房': [2150, 2224, 2251, 2637], '大山子租房': [583, 696, 1682, 2001], '大峪租房': [369, 431, 826, 844, 862, 877, 1553, 1584, 1588, 1591, 2360, 2362], '大望路租房': [32, 661, 676, 720, 891, 892, 1272, 1362, 1386, 1450, 1994, 2230, 2638, 2640, 2668, 2670], '大红门租房': [781, 2394], '天坛租房': [1101, 1138, 2328, 2388], '天宁寺租房': [31, 76, 223, 290, 667, 740, 1033, 1167, 1459, 1472, 1967, 2202, 2240], '天宫院租房': [1713, 1802], '天通苑租房': [3, 35, 78, 148, 189, 295, 351, 387, 390, 458, 463, 557, 687, 763, 934, 957, 1055, 1069, 1075, 1089, 1097, 1327, 1372, 1374, 1400, 1402, 1410, 1608, 1632, 1904, 1905, 1919, 1933, 1996, 2121, 2141, 2468, 2663, 2749], '太平桥租房': [424, 500, 529, 727, 840, 1012, 1270], '太阳宫租房': [459, 665, 689, 864, 879, 1125, 1196, 1445, 1454, 1567, 1638, 1744, 1752, 1916, 2012, 2472, 2568, 2756], '奥林匹克公园租房': [93, 129, 283, 352, 422, 553, 701, 856, 1184, 1394, 2504, 2549, 2559, 2705, 2727, 2746], '学院路租房': [1042, 1078, 1118, 1189, 1759, 2043, 2232, 2465, 2662], '安宁庄租房': [604, 1104, 1970, 2236, 2261, 2284], '安定门租房': [47, 63, 91, 92, 212, 420, 695, 825, 873, 970, 1609, 1763, 2024, 2301, 2479, 2491, 2513, 2730], '安贞租房': [133, 269, 277, 292, 377, 402, 406, 501, 530, 587, 656, 750, 798, 1056, 1149, 1322, 1366, 1390, 1463, 1648, 1662, 1698, 1712, 1995, 1997, 2120, 2140, 2475, 2528, 2575], '宋家庄租房': [400, 1046, 1131, 1801, 1907, 2291, 2592, 2690, 2703], '官园租房': [23, 101, 167, 175, 178, 196, 243, 505, 534, 717, 744, 1072, 1094, 1452, 1460, 1473, 1707, 1710, 1778, 2050], '定慧寺租房': [51, 502, 506, 531, 535, 590, 628, 843, 1250, 1289], '定福庄租房': [1011, 1062, 1082, 1201, 1262, 1319, 1323, 1333, 1354, 1546, 1593, 2476, 2630, 2736], '宣武门租房': [208, 216, 398, 712, 860, 865, 1052, 1370, 1398, 1478, 1514, 1520, 2420, 2545, 2555, 2561], '小西天租房': [8, 239, 267, 273, 1407, 1438, 1771, 2692], '岳各庄租房': [293, 598, 1506, 1571, 1660, 1708, 2619], '崇文门租房': [1107, 1178, 1541, 1715, 2089, 2112, 2256, 2282, 2649, 2677], '工体租房': [100, 164, 232, 423, 552, 723, 736, 942, 945, 1377, 1411, 1551, 1598, 1743, 1859, 2093, 2109, 2390, 2719], '左安门租房': [355, 556, 1077, 1099, 1925, 2414], '常营租房': [102, 188, 471, 570, 601, 686, 703, 918, 1287, 1292, 1507, 1576, 1793, 1809, 1869, 1937, 1992, 2639, 2641], '广安门租房': [2, 26, 30, 45, 48, 61, 64, 106, 128, 206, 214, 268, 272, 386, 766, 850, 971, 973, 978, 1117, 1143, 1155, 1188, 1409, 1415, 1481, 1483, 1499, 1664, 1754, 1790, 1806, 2238, 2349, 2444, 2716], '广渠门租房': [98, 99, 194, 221, 820, 972, 1019, 1022, 1064, 1084, 1273, 1311, 1430, 1442, 1484, 1575, 1676, 2037, 2081, 2085, 2100, 2322, 2563], '建国门内租房': [436, 688, 1544, 1615], '建国门外租房': [350, 902, 1429, 2027, 2257, 2733], '德胜门租房': [311, 573, 691, 1276], ...}

In [51]:
df_gby.get_group('CBD租房')

         区域       地址    户型   面积     价格     朝向        更新时间  看房人数
624   CBD租房   和乔丽致公寓  1室1厅   61  12000      北  2017.07.27     2
645   CBD租房   和乔丽致公寓  1室1厅   61  12000      北  2017.07.27     2
693   CBD租房  SOHO现代城  3室1厅  143  15000      西  2017.07.14    31
1359  CBD租房   和乔丽致公寓  1室1厅   61  11000      西  2017.07.15     3
1363  CBD租房     盛世嘉园  2室2厅  161  16000      南  2017.07.27     1
1383  CBD租房   和乔丽致公寓  1室1厅   61  11000      西  2017.07.15     3
1387  CBD租房     盛世嘉园  2室2厅  161  16000      南  2017.07.27     1
1719  CBD租房  SOHO现代城  3室1厅  178  22000      南  2017.07.27     0
1755  CBD租房   金地国际花园  3室1厅  197  27000   西南 北  2017.07.15     6
1840  CBD租房   金地国际花园  2室1厅  124  19000      南  2017.07.18    16
1864  CBD租房   金地国际花园  2室1厅  124  19000      南  2017.07.18    16
1958  CBD租房     盛世嘉园  2室1厅  132  13000  南 西 北  2017.07.24     4
1993  CBD租房    阳光100  4室2厅  173  18000  东南 东北  2017.07.14     3
2073  CBD租房     光辉南里  1室1厅   55   6200    东 南  2017.07.21     9
2288  CBD租房  建国路100号  2室1厅   61   6000      东  2017.07.20     2
2562  CBD租房   和乔丽致公寓  1室1厅   61  12000      北  2017.07.14     9

In [57]:
s_gby = df_gby['价格']
s_gby.get_group('CBD租房').mean()

14700.0

In [47]:
s_gby.mean()

区域
CBD租房      14700.000000
七里庄租房       5617.647059
万寿路租房       6575.000000
万柳租房       18629.166667
三元桥租房      12581.818182
               ...
鲁谷租房        6381.578947
黄村中租房       3775.000000
黄村北租房       5631.578947
黄村火车站租房     3166.666667
鼓楼大街租房      3987.500000
Name: 价格, Length: 208, dtype: float64

In [70]:
def func(s):
    print(s)
    print(type(s))    
    print('=====================')
    # 每一组选出价格>3000的 对这部分求平均
    result = s[s<12000].mean()
    return result
## 自定义聚合函数
df.groupby(['区域'])['价格'].agg(func)

624     12000
645     12000
693     15000
1359    11000
1363    16000
1383    11000
1387    16000
1719    22000
1755    27000
1840    19000
1864    19000
1958    13000
1993    18000
2073     6200
2288     6000
2562    12000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
117     6500
138     5500
144     6500
154     5500
297     5600
300     5600
1065    4500
1085    4500
1440    9000
1516    6100
1941    5500
1952    5700
1962    5200
1963    6200
2099    4400
2189    4600
2191    4600
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
168      6100
466      5000
469      6000
968     10000
1466     7500
1881     4500
2338     6500
2655     7000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
233     12500
464     18000
467     25000
481     22000
510     22000
589     21000
596     12000
627     21000
671     25000
851     18500
853     27000
917     17000
952     25600
1235    14000
1240    21000
1471    22000
1497    18000
1517    24000
1690    17000
1846    15000
2418     8500
2495    24000
2574    11000
2631     6000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
95      27000
245      6000
338     26000
699      5500
777      5600
802      5500
811      5500
1109    13000
1197    13000
1216    13000
1512    16000
1518    15500
1572     4500
1798    12000
1818    12000
1843     6500
1942    25000
1949    18000
1978    18000
2065    14000
2277     9000
2759     6200
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
753      7000
793      7000
1162     7000
1275    26000
2152     8000
2488    26000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
54       4600
67       4600
68       4600
169      7000
885      7500
1223     4600
1245    12000
1618    12000
2149     6000
2183     6000
2417     4500
2433     9000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
171      8500
222      9500
281      7500
320      8500
339     25000
858     12000
1024     6390
1449    14800
1464    14000
1741    10000
1751    14000
1772    12000
2011    15500
2013    22500
2497    17500
2712    13500
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
335     7500
617     2500
638     2500
678     3700
965     6700
980     2900
1081    2500
1335    4000
1749    3300
2095    2700
2226    2300
2428    4500
2474    3000
2493    3000
2613    2700
2731    2500
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
2187    5000
2584    9000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
75     6000
97     7000
546    4500
845    3400
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
1051    26000
1770    18500
2115     5800
2135     5800
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
58       6300
116     23000
136      7000
152      7000
220     15000
226      5800
240      6500
381      8500
405      8500
488      6500
517      6500
575     14000
662     36500
1255    11500
1281    20000
1543     6500
1582     9500
1590     6500
1666    14000
2706     6800
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
473      6800
1171     6500
1498     6500
1548    10000
1595    10000
1748     5800
2003     6600
2688    25000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
1017    7200
1110    7500
1179    7300
1294    6800
2218    6700
2219    5800
2220    5800
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
84      2900
694     3500
775     5600
1035    3400
1038    2500
1330    4500
1480    3600
1495    3500
1540    4600
1574    4600
1637    7600
1746    3300
1799    4000
1819    4000
1820    3500
1842    5000
1866    5000
2459    3700
2734    5500
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
1885    5600
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
87      2700
461     4200
569     3900
602     3800
956     3600
1358    3200
1360    4100
1382    3200
1384    4100
1663    3300
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
404      4100
716      4300
875      3100
886      4200
1036     2900
1211     4000
1487     5800
1515     7600
1533    16000
1555     3200
1601     3200
1703     3000
1756     2900
1796     3500
1812     3500
1897     3500
2032     6000
2039     3300
2041     3300
2042     5300
2123     3300
2143     3300
2320     4200
2462     2800
2542     4100
2552     4100
2609     3500
2729     3100
2748     3100
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
110    8500
384    6300
815    5500
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
140      5500
156      5500
263      6500
626      9000
647      9000
725     15000
991      5200
1102    11500
1139    11500
1237     6000
1494     6500
1504     6500
1868     5500
2464     5000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
271      7000
499      7000
528      7000
565     13500
995      6500
1529     8500
1531     8500
2131     6000
2161     6000
2206    13500
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
2264    4800
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
279      6200
599      6500
735      6200
1199     8300
1247     6500
1277     8000
1300    23000
1392     9500
1405     8000
1412     8000
1524     7500
1573     5900
1617     7500
1757    16000
1862     8200
1886    12000
1888     9800
1906     9200
2084     5800
2145     8000
2198    14000
2416     8500
2535     9200
2544    22000
2554    22000
2577    12000
2629    16000
2678     8000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
385      7500
491      7900
520      7900
568      4800
883     14500
1050    12000
1060     6000
1068     6000
1088     6000
1093     6000
1166     6700
1185     9200
1538     4500
1562    10000
1786     6000
1821     5300
1826    14000
2134     4600
2164     4600
2356     4500
2471     6500
2635     6000
2687     6000
2699    15000
2700    15000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
244     8500
768     6800
808     6800
2614    8700
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
328     8500
1557    5500
2652    7200
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
210      6700
234      4300
284      5600
359      7000
364      7000
564      6300
884      7500
1008     3500
1023     3200
1115     3100
1157     5000
1207     6500
1453     7500
1511     5500
1530     8000
1535    11000
1622     2800
1654     7500
1822     7300
1841     7000
1858     7800
1865     7000
1895     7500
1930     4900
1968     4600
2242     3500
2254     3500
2305     4600
2537     6350
2567     7500
2579     6300
2581     6300
2597     5500
2599     7800
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
11     6300
749    6800
761    6800
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
287      6000
315      5000
452      6500
588      5800
707      5500
788      5800
1251    11000
1308     5500
1309     5000
1378     5800
1677     5000
2222     7200
2234     9200
2713    15000
2737    15000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
29       6000
33      11000
141      6300
147      6000
157      6300
396      4200
419      5500
581      5800
713      6800
1145     8500
1177     6600
1206     4200
1214     5200
1345     6500
1416     6300
1623     6000
1624     4500
2002     8100
2247     6300
2273     6300
2325     6000
2419    16000
2757     7200
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
450     5200
764     7000
927     7500
1129    5000
1625    6200
1669    5500
2129    8200
2266    6200
2337    6600
2376    6200
2715    5500
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
163      6000
484      5000
513      5000
566      8500
784      5500
923      5000
1426    10500
1893     5800
2500     7200
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
1556    4900
1602    4900
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
683    4500
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
15      3700
1564    5800
1792    5500
1808    5500
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
118      5400
145      5400
195      5300
323      6000
330     16000
344      6500
347      6500
451      4000
595      5400
771      8000
915      6000
1004    16800
1257     5200
1260     5200
1545     5500
1592     5500
2096     5800
2396     4800
2436     4900
2438     4200
2708     4600
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
409      3500
540      3700
544      3000
726      9000
812      3000
878     13000
983     11000
1000    11000
1034     4000
1424     4000
1462     4000
1702     5500
1829     3400
1956     4400
2004    17000
2197     4000
2445     4300
2517     8500
2519     4500
2523     8500
2525     4500
2531     5500
2586     4500
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
456     8000
800     5000
1198    3600
1222    3600
1321    4200
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
310     3800
509     3100
538     3100
591     1500
629     1500
909     2900
1170    3800
1689    4500
1692    4500
1800    3700
1828    2800
1914    3200
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
24      4500
247     3200
368     3500
430     3500
1133    5200
1271    3800
1542    5200
1563    3800
1725    4500
1726    3800
2087    4000
2102    4000
2172    4800
2208    4500
2645    4600
2647    4000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
2014    4300
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
813      4000
1030     5500
1284    15000
2298     5700
2622     4600
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
6       7500
9       5300
18      5500
96      9000
114     6800
        ...
2642    8500
2644    8500
2656    9000
2697    4600
2726    4600
Name: 价格, Length: 79, dtype: int64
<class 'pandas.core.series.Series'>
=====================
199      8500
425      5200
504      8200
533      8200
881     13500
899      9200
943     12800
1479     4800
1508    13000
1630     5700
1817    17000
1965    11500
2059     7500
2062     7600
2210     5900
2480    13500
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
348     4200
1236    5100
1554    5000
1600    5000
2314    8200
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
2610    1800
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
266      5000
1021     4900
1338     5100
1490    15900
1500    15900
1979     7500
2056     5200
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
185     4200
1745    2900
1857    3300
1951    3500
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
74      3100
414     2900
449     3300
705     4300
759     3200
797     3200
1151    4200
1175    3200
1626    4100
1876    5700
2159    3100
2170    3100
2195    2700
2422    4300
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
2306    5300
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
14      32000
34       9300
71      16500
113      6000
123     14000
201      9500
227     14500
291      7500
305     11000
388     16500
394     16500
468     16700
485     12000
514     12000
558      9500
664     32000
666     23000
704      9500
708     20000
722     20000
774     15500
935     11500
951      9500
966      9500
1025     8500
1028     9000
1043     8200
1213    12000
1215     7000
1229    13000
1246    13500
1314     5600
1441     9500
1448    11500
1475     8500
1493    11000
1503    11000
1678    14500
1838    12500
1860    12500
1973     6600
1983     6600
2015    26000
2020     8500
2026     8700
2051     7000
2171    17000
2365     8300
2412     6000
2421     8500
2501    30000
2507    15500
2533    30000
2570    12000
2604    14000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
83       5800
1066     4600
1086     4600
1254     4300
1616     3800
1627     4200
1934     9000
2097    10000
2389     4700
2455     3500
2588     8200
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
249      5500
801      7000
810      7000
1176     6800
1230     7200
1231     7200
1670     8300
2255     6200
2672    12500
2752    10000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
700     3800
1659    4700
2276    6000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
987     4500
989     7800
1002    7800
1347    8500
2066    8000
2547    4300
2557    4300
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
805     4700
814     4000
818     4700
1063    4500
1083    4500
1279    5500
1339    3800
1668    4300
1739    5200
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
371      4500
433      4500
828      4300
907     15000
1009     5600
1269     4400
1521     5000
1532    34000
1649     5000
1680     6500
1825    15000
1887     4500
2071     6300
2106     5000
2373    11000
2423    11000
2548     4500
2558     4500
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
1071    4500
1091    4500
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
10        7600
108       4600
262       8200
264       8300
417       5800
739       5600
789       5700
1039      6100
1146      6300
1224      6200
1225      6200
1552      5300
1599      5300
1644      6500
1657      6500
2047     13000
2088      5500
2111      5500
2249      6800
2275      6800
2289      6200
2370      5300
2374      6300
2658    210000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
19       5200
107      5000
382     13000
619      8600
640      8600
911     17000
949     11000
1045     8500
1127    19000
1268     4500
1310     6300
1486     9400
1650     6000
1890    10000
1910     9000
2538    13000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
104      6500
721      5000
752      5500
792      5500
1018     9300
1135     4700
1174     9700
1742     6000
1753     5000
1774    25000
1791    10000
1807    10000
1856     7000
2114     8300
2217    10000
2228     6500
2252     6500
2453     5200
2650     6000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
5        4000
25       6300
46       4000
62       4000
82       6100
85       7600
135      5800
246      3800
288      4000
321      4700
345      4100
357      6500
362      6500
416      5000
454      5000
496      4600
525      4600
548      6800
551      5200
600      6500
636      4200
779      5000
830      3600
847      3600
905     14000
947      5200
1014     4300
1317     6700
1352     6700
1355     5700
1419     5600
1423     4500
1465     4200
1651     7500
1673     4200
1803     6700
1918     5800
1932     5800
1990     3600
2300     6200
2344     4000
2601     3700
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
4       6400
238     6200
979     6200
1079    5200
1137    5200
1140    6500
1944    5500
1945    7800
1974    7800
2304    6000
2327    6000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
455      5000
839      6000
1451    15000
1711    18500
2053     5000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
256    7500
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
580     7600
620     5500
641     5500
2190    4300
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
754     2600
794     2600
1003    5000
2681    3500
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
2150    2800
2224    3000
2251    3000
2637    3200
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
583      5500
696      8500
1682    13000
2001    30000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
369     3550
431     3550
826     2700
844     3000
862     2600
877     3400
1553    2600
1584    2300
1588    2700
1591    2600
2360    3000
2362    3100
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
32       6100
661      8300
676      5000
720     15000
891     13000
892     12000
1272    13000
1362     9000
1386     9000
1450     9500
1994    18000
2230     7200
2638     5500
2640     5500
2668    17000
2670    17000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
781     8600
2394    7500
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
1101    9000
1138    9000
2328    4800
2388    5400
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
31      5100
76      7300
223     7300
290     4300
667     4600
740     4800
1033    6500
1167    4300
1459    5700
1472    5700
1967    6200
2202    5000
2240    5500
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
1713    3000
1802    3800
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
3        5300
35       4200
78       4500
148      5500
189      5000
295      5300
351     16000
387      6800
390      6800
458      7700
463      6000
557      4500
687      4200
763      5000
934      5500
957      7800
1055     5700
1069     4500
1075     5900
1089     4500
1097     5900
1327     4800
1372     9000
1374     5800
1400     9000
1402     5800
1410     5000
1608     6000
1632    15000
1904     6000
1905    12000
1919     7500
1933     7500
1996     9500
2121     4100
2141     4100
2468     5500
2663     6500
2749     5000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
424     3800
500     6400
529     6400
727     4300
840     4200
1012    4500
1270    5000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
459     16000
665      6800
689     12000
864     23000
879     13500
1125    11000
1196    11000
1445    21000
1454    20000
1567    14000
1638    30000
1744    12800
1752    20000
1916    20000
2012    36000
2472    30000
2568    17000
2756     9500
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
93       9200
129     11500
283      6500
352     21000
422     13500
553      6300
701     22000
856     20000
1184     8100
1394    13000
2504     8800
2549     9300
2559     9300
2705     5500
2727    14000
2746    14000
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
1042     6800
1078    12500
1118     8000
1189     8000
1759     8500
2043     6800
2232     6000
2465     6900
2662    15500
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
604     6000
1104    4600
1970    6800
2236    4800
2261    4600
2284    5500
Name: 价格, dtype: int64
<class 'pandas.core.series.Series'>
=====================
47       6800
63       6800
91      12000
92      16800
212      9500

区域
CBD租房      8550.000000
七里庄租房      5617.647059
万寿路租房      6575.000000
万柳租房       8500.000000
三元桥租房      6033.333333
              ...
鲁谷租房       6013.888889
黄村中租房      3775.000000
黄村北租房      5631.578947
黄村火车站租房    3166.666667
鼓楼大街租房     3987.500000
Name: 价格, Length: 208, dtype: float64

In [71]:
df[df['区域']=='金宝街租房']

        区域    地址    户型   面积     价格   朝向        更新时间  看房人数
475  金宝街租房  禾风相府  3室1厅  163  32000  南 北  2017.07.27    13

In [73]:
df['价格'].describe()

count      2760.000000
mean       7570.800725
std        6316.204986
min        1300.000000
25%        4500.000000
50%        6000.000000
75%        8500.000000
max      210000.000000
Name: 价格, dtype: float64

In [ ]:
# 价格低于4500 低    4500~8500 中  >8500 高

In [75]:
def get_price_label(price):
    if price<=4500:
        return '低'
    elif price<=8500:
        return '中'
    else:
        return '高'
    
df['价格'].apply(get_price_label).value_counts()

中    1399
低     725
高     636
Name: 价格, dtype: int64

In [77]:
df[df['价格']>8500].shape[0]

636

In [80]:
pd.cut(df['价格'],bins=3).value_counts()

(1091.3, 70866.667]        2759
(140433.333, 210000.0]        1
(70866.667, 140433.333]       0
Name: 价格, dtype: int64

In [82]:
df['价格'].min()

1300

In [79]:
1091.3-70866.667

-69775.367

In [81]:
140433.333-210000.0

-69566.66699999999

In [85]:
pd.cut(df['价格'],bins=[0,4500,8500,210000],labels=['低','中','高']).value_counts()

中    1399
低     725
高     636
Name: 价格, dtype: int64

In [91]:
pd.cut(df['价格'],bins=[1300,4500,8500,210000],labels=['低','中','高']).sort_values(ascending=False)

652       高
738       高
1916      高
1913      高
742       高
       ...
2168      低
2170      低
1605      低
2279      低
2527    NaN
Name: 价格, Length: 2760, dtype: category
Categories (3, object): ['低' < '中' < '高']