In [9]:
import pandas as pd
titanic_df = pd.read_csv('C:/Develop/深圳42/data/titanic_train.csv')
# kaggle.com

In [2]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

- passengerid： 乘客 ID
- class： 舱位等级 (1 = 1st, 2 = 2nd, 3 = 3rd)
- name： 乘客姓名
- sex： 性别
- age： 年龄
- sibsp： 在船上的兄弟姐妹／配偶个数
- parch： 在船上的父母／小孩个数
- ticket： 船票信息
- fare： 票价
- cabin： 客舱
- embarked： 登船港口 (C = Cherbourg, Q = Queenstown, S = Southampton)
- survived:  值 0 或 1（这里 1 表示幸存，0 表示遇难）

- ① 计算每一列缺失值比例

In [4]:
titanic_df.isnull().sum()/titanic_df.shape[0]

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.198653
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.771044
Embarked       0.002245
dtype: float64

In [3]:
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

- ② 用平均年龄给Age列填充缺失值

In [6]:
titanic_df['Age'].fillna(titanic_df['Age'].mean(), inplace=True)

In [8]:
titanic_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

- ③ 找到数据中相关性较强的列, 并对其做简单说明

In [10]:
titanic_df.corr()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_10740\156109008.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  titanic_df.corr()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

- ④ 统计哪个港口登船的人最多

In [11]:
titanic_df['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

- ⑤ 乘客姓名中 有些人的名字里包含了特殊的信息 ['Lady', 'Countess','Capt', 'Col','Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 添加一列 身份 'Rare' / 'Norm'

In [4]:
titanic_df['Name'].head(10)

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
5                                     Moran, Mr. James
6                              McCarthy, Mr. Timothy J
7                       Palsson, Master. Gosta Leonard
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                  Nasser, Mrs. Nicholas (Adele Achem)
Name: Name, dtype: object

In [17]:
list_1 = ['Lady.', 'Countess.','Capt.', 'Col.','Don.', 'Dr.', 'Major.', 'Rev.', 'Sir.', 'Jonkheer.', 'Dona.']
def func(name):
    # 遍历 特殊称呼列表
    for str in list_1:
        # 如果 在名字中包含了一个特殊称呼
        if str in name:
            # 返回 Rare
            return 'Rare'
        # else:
        #     return ''
    # 所有的特殊称呼都遍历一圈, 没有在名字里, 返回Norm
    return 'Norm'
titanic_df['Name'].apply(func).value_counts()

Norm    868
Rare     23
Name: Name, dtype: int64

In [18]:
titanic_df['cate'] = titanic_df['Name'].apply(func)

In [19]:
titanic_df[titanic_df['cate']=='Rare']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,cate
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C,Rare
149,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S,Rare
150,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S,Rare
245,246,0,1,"Minahan, Dr. William Edward",male,44.0,2,0,19928,90.0000,C78,Q,Rare
249,250,0,2,"Carter, Rev. Ernest Courtenay",male,54.0,1,0,244252,26.0000,NaN,S,Rare
317,318,0,2,"Moraweck, Dr. Ernest",male,54.0,0,0,29011,14.0000,NaN,S,Rare
398,399,0,2,"Pain, Dr. Alfred",male,23.0,0,0,244278,10.5000,NaN,S,Rare
449,450,1,1,"Peuchen, Major. Arthur Godfrey",male,52.0,0,0,113786,30.5000,C104,S,Rare
536,537,0,1,"Butt, Major. Archibald Willingham",male,45.0,0,0,113050,26.5500,B38,S,Rare
556,557,1,1,"Duff Gordon, Lady. (Lucille Christiana Sutherl...",female,48.0,1,0,11755,39.6000,A16,C,Rare
599,600,1,1,"Duff Gordon, Sir. Cosmo Edmund (""Mr Morgan"")",male,49.0,1,0,PC 17485,56.9292,A20,C,Rare
626,627,0,2,"Kirkland, Rev. Charles Leonard",male,57.0,0,0,219533,12.3500,NaN,Q,Rare
632,633,1,1,"Stahelin-Maeglin, Dr. Max",male,32.0,0,0,13214,30.5000,B50,C,Rare
647,648,1,1,"Simonius-Blumer, Col. Oberst Alfons",male,56.0,0,0,13213,35.5000,A26,C,Rare
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.0,2,0,PC 17611,133.6500,NaN,S,Rare
694,695,0,1,"Weir, Col. John",male,60.0,0,0,113800,26.5500,NaN,S,Rare
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S,Rare
759,760,1,1,"Rothes, the Countess. of (Lucy Noel Martha Dye...",female,33.0,0,0,110152,86.5000,B77,S,Rare
766,767,0,1,"Brewe, Dr. Arthur Jackson",male,NaN,0,0,112379,39.6000,NaN,C,Rare
796,797,1,1,"Leader, Dr. Alice (Farnham)",female,49.0,0,0,17465,25.9292,D17,S,Rare
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0000,NaN,S,Rare
848,849,0,2,"Harper, Rev. John",male,28.0,0,1,248727,33.0000,NaN,S,Rare
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Rare

- ⑥ 将年龄分成几组 0~18 未成年 18~35 青年 35~60 中年 >60 老年 并计算不同年龄段的生还率

In [21]:
titanic_df['年龄段'] =pd.cut(titanic_df['Age'], bins=[0,18,35,60,100], labels=['未成年', '青年','中年','老年'])

In [22]:
titanic_df['年龄段'].value_counts()

青年     358
中年     195
未成年    139
老年      22
Name: 年龄段, dtype: int64

In [23]:
titanic_df.groupby('年龄段')['Survived'].mean()

年龄段
未成年    0.503597
青年     0.382682
中年     0.400000
老年     0.227273
Name: Survived, dtype: float64

In [ ]:
# 生还的人数/总人数  
# Survived平均 = titanic_df['Survived'].sum()/len(titanic_df)
# 违约   1 违约 0 正常还钱

- ⑦计算不同仓位等级的乘客的生还率

In [24]:
titanic_df.groupby('Pclass')['Survived'].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

- ⑧简单分析哪类人群生还率更高

In [25]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'cate', '年龄段'],
      dtype='object')

In [27]:
titanic_df.groupby('Sex')['Survived'].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [28]:
titanic_df.groupby(['Sex','Pclass','年龄段'])['Survived'].mean()

Sex     Pclass  年龄段
female  1       未成年    0.909091
                青年     0.972222
                中年     0.972222
                老年     1.000000
        2       未成年    1.000000
                青年     0.925000
                中年     0.850000
                老年          NaN
        3       未成年    0.511628
                青年     0.500000
                中年     0.142857
                老年     1.000000
male    1       未成年    0.800000
                青年     0.500000
                中年     0.370370
                老年     0.083333
        2       未成年    0.600000
                青年     0.074074
                中年     0.037037
                老年     0.333333
        3       未成年    0.215686
                青年     0.155844
                中年     0.068182
                老年     0.000000
Name: Survived, dtype: float64

In [31]:
titanic_df[(titanic_df['Pclass']==1) & (titanic_df['Sex']=='female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,cate,年龄段
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Norm,中年
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Norm,青年
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,Norm,中年
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C,Norm,NaN
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C,Norm,中年
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S,Norm,中年
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S,Norm,中年
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,Norm,中年
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,Norm,中年
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Norm,青年